//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echiquier_de_Bezzel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AntiqueWhite")]
        public global::System.Drawing.Color Couleur_Damier_A {
            get {
                return ((global::System.Drawing.Color)(this["Couleur_Damier_A"]));
            }
            set {
                this["Couleur_Damier_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkKhaki")]
        public global::System.Drawing.Color Couleur_Damier_B {
            get {
                return ((global::System.Drawing.Color)(this["Couleur_Damier_B"]));
            }
            set {
                this["Couleur_Damier_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color Couleur_toucherParUneReine {
            get {
                return ((global::System.Drawing.Color)(this["Couleur_toucherParUneReine"]));
            }
            set {
                this["Couleur_toucherParUneReine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color Couleur_TrajectoireReine_Tout_Afficher {
            get {
                return ((global::System.Drawing.Color)(this["Couleur_TrajectoireReine_Tout_Afficher"]));
            }
            set {
                this["Couleur_TrajectoireReine_Tout_Afficher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Couleur_TrajectoireReine {
            get {
                return ((global::System.Drawing.Color)(this["Couleur_TrajectoireReine"]));
            }
            set {
                this["Couleur_TrajectoireReine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrajectoireReineCouleurDifférente {
            get {
                return ((bool)(this["TrajectoireReineCouleurDifférente"]));
            }
            set {
                this["TrajectoireReineCouleurDifférente"] = value;
            }
        }
    }
}
